name: Feature request
description: Suggest a new feature or improvement
title: "Feature: "
labels:
  - enhancement
  - needs-triage
assignees:
  - klejejs

body:
  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.

  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    validations:
      required: true
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: debug_file_data
    validations:
      required: true
    attributes:
      label: Debug File Data
      description: Please attach Thermia debug file data that can help diagnose the issue. To get the debug file data, see [README.md](https://github.com/klejejs/ha-thermia-heat-pump-integration?tab=readme-ov-file#adding-support-for-new-heat-pump-models).

  - type: checkboxes
    id: latest_version
    attributes:
      label: Are you running the latest version?
      description: Please check if you are running the latest version of the integration before submitting a bug report.
      options:
        - label: I have checked and am running the latest version of the integration
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
