name: Check version updates for integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_and_create_pr:
    name: Check and create PR if necessary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U lastversion
      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: Check for updates
        run: ./scripts/update_ThermiaOnlineAPI_version.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_FOR_GITHUB_ACCESS }}
          commit-message: Update ThermiaOnlineAPI version to ${{ env.LATEST_API_VERSION }}
          title: Update ThermiaOnlineAPI version to ${{ env.LATEST_API_VERSION }}
          body: |
            This PR updates the ThermiaOnlineAPI version to the latest version which is ${{ env.LATEST_API_VERSION }}.
          branch: update-dependencies
          delete-branch: true
