name: Package assets

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Zip release assets
        run: zip -r thermia.zip custom_components
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: thermia.zip
          asset_name: thermia.zip
          tag: ${{ github.ref }}
          overwrite: true
